[package]
name = "firecore-dependencies"
version = "0.5.0-beta.2021-06-19"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[features]
default = []
# log = ["log"]
str = ["tinystr"]
vec = ["arrayvec"]
hash = ["ahash"]
engine = ["tetra"]
audio = ["tetra/audio", "tetra/audio_vorbis"]
static-link = ["tetra/sdl2_static_link"]
bundled = ["tetra/sdl2_bundled"]
ser = ["bincode"]
random = []
borrow = ["serde"]
script = ["rhai"]

[dependencies]

log = { version = "0.4", optional = true }

tinystr = { version = "0.4", features = ["serde"], optional = true }
arrayvec = { version = "0.5", features = ["serde"], optional = true }
ahash = { version = "0.7", features = ["serde"], optional = true }

# postcard = { version = "0.6", default-features = false, features = ["alloc"], optional = true }
bincode = { version = "1.3", optional = true }

tetra = { path = "../../../../firecore/tetra", default-features = false, features = ["serde_support", "texture_png"], optional = true }

serde = { version = "1.0", features = ["derive"], optional = true }

rhai = { version = "0.20", optional = true } # maybe look into going back to smallvec

[[example]]
name = "random"
required-features = ["random"]