[package]
name = "firecore-input"
version = "0.3.0-beta.4"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[dependencies]

macroquad = { git = "https://github.com/DoNotDoughnut/macroquad" }

serde = { version = "1.0", features = ["derive"] }

firecore-util = { git = "https://github.com/DoNotDoughnut/firecore-util", default-features = false, features = ["hash"] }